In [2]:
import numpy as np

# using randn function

In [3]:
data = np.random.randn(2,3)
data

array([[ 0.33697075, -0.66533788,  1.03824503],
       [ 0.30495357,  0.05378034, -0.37696617]])

In [4]:
data * 10

array([[ 3.36970747, -6.65337878, 10.38245031],
       [ 3.04953569,  0.53780338, -3.76966172]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

# creation of array

In [7]:
data1 = [6, 7.5, 8, 0, 1]

In [8]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# creating empty arrays

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
# (times, rows, columns)
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

# creating string type array

In [15]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

# type conversion

In [16]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [17]:
int_arr = np.arange(10)
int_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
float_arr = np.array([1, 2, 3, 4], dtype = np.float64)
float_arr

array([1., 2., 3., 4.])

In [19]:
int_arr.astype(float_arr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# batchprocessing using arrays

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [22]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [24]:
arr ** 5

array([[1.000e+00, 3.200e+01, 2.430e+02],
       [1.024e+03, 3.125e+03, 7.776e+03]])

In [25]:
arr2 = np.array([[12, 1, 4], [2, 3, 18]], dtype = np.float64)
arr2

array([[12.,  1.,  4.],
       [ 2.,  3., 18.]])

In [26]:
arr2 > arr

array([[ True, False,  True],
       [False, False,  True]])

# Indexing

In [27]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [31]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

## slice effects the original array

In [32]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [33]:
arr_slice = arr[5:8].copy()
arr_slice

array([   12, 12345,    12])

In [34]:
arr_slice[1] = 12
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d[2]

array([7, 8, 9])

In [37]:
arr2d[0][2]

3

In [38]:
arr2d[0, 2]

3

In [39]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr3d[0][1]

array([4, 5, 6])

In [42]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# indexing with slices

In [45]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [48]:
arr2d[:, 2]

array([3, 6, 9])

# Boolean indexing (always creates a copy)

In [49]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [50]:
data = np.random.randn(7 ,4)
data

array([[ 0.55524818, -1.37518902, -2.20039278, -0.71072835],
       [-0.86814469, -0.72379373, -0.43303205, -0.03871074],
       [ 0.91188388,  0.857123  ,  0.07800703,  0.62360688],
       [ 0.77998341,  1.47468538, -1.3809718 ,  0.84737589],
       [-0.06505546, -1.77045589,  0.25616448,  0.01958831],
       [-0.01739505,  0.23840014,  0.70173973,  0.10894902],
       [ 0.28398604, -0.81066827, -0.89165016,  0.20034175]])

In [51]:
'bob' in names

True

In [52]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [53]:
# rows in data with same index bob == true
data[names == 'bob']

array([[ 0.55524818, -1.37518902, -2.20039278, -0.71072835],
       [ 0.77998341,  1.47468538, -1.3809718 ,  0.84737589]])

In [54]:
data[names == 'bob', 2:]

array([[-2.20039278, -0.71072835],
       [-1.3809718 ,  0.84737589]])

In [55]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True])

In [56]:
data[names != 'bob']

array([[-0.86814469, -0.72379373, -0.43303205, -0.03871074],
       [ 0.91188388,  0.857123  ,  0.07800703,  0.62360688],
       [-0.06505546, -1.77045589,  0.25616448,  0.01958831],
       [-0.01739505,  0.23840014,  0.70173973,  0.10894902],
       [ 0.28398604, -0.81066827, -0.89165016,  0.20034175]])

In [57]:
cond = names == 'bob'
cond

array([ True, False, False,  True, False, False, False])

In [58]:
data[cond]

array([[ 0.55524818, -1.37518902, -2.20039278, -0.71072835],
       [ 0.77998341,  1.47468538, -1.3809718 ,  0.84737589]])

In [59]:
data[~cond]

array([[-0.86814469, -0.72379373, -0.43303205, -0.03871074],
       [ 0.91188388,  0.857123  ,  0.07800703,  0.62360688],
       [-0.06505546, -1.77045589,  0.25616448,  0.01958831],
       [-0.01739505,  0.23840014,  0.70173973,  0.10894902],
       [ 0.28398604, -0.81066827, -0.89165016,  0.20034175]])

In [60]:
mask = (names == 'bob') | (names == 'will')
mask

array([ True, False,  True,  True,  True, False, False])

In [61]:
data[mask]

array([[ 0.55524818, -1.37518902, -2.20039278, -0.71072835],
       [ 0.91188388,  0.857123  ,  0.07800703,  0.62360688],
       [ 0.77998341,  1.47468538, -1.3809718 ,  0.84737589],
       [-0.06505546, -1.77045589,  0.25616448,  0.01958831]])

# Fancy Indexing

In [62]:
arr = np.empty((8,4))
arr

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.24399158e-314,
        2.12199579e-314],
       [8.00810472e+033, 1.85885603e+260, 5.94158821e-313,
        2.97079411e-313],
       [4.00536382e-307, 1.78020576e-306, 3.56022683e-307,
        4.45057636e-308],
       [4.45044056e-308, 1.11261095e-306, 2.11387449e-307,
        1.60221072e-306],
       [9.34604358e-307, 5.63234836e-322, 0.00000000e+000,
        0.00000000e+000]])

In [63]:
for i in range(8):
    arr[i] = i
arr
# to make the output more apparent

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [64]:
arr[[4, 3, 0, 6]] # selecting rows in any order

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [66]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [67]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [70]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # elements 1,0 ; 5,3 ...

array([ 4, 23, 29, 10])