In [14]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

# Series

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2[['a', 'b', 'c']]

a   -5
b    7
c    3
dtype: int64

In [12]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [18]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [20]:
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
obj3 + obj4
# automatic alignment of index labels

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [28]:
obj4.name = 'population'

In [31]:
obj.index.name = 'state'

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj

state
0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj.index = ['bob', 'steve', 'jeff', 'ryan']
obj

bob      4
steve    7
jeff    -5
ryan     3
dtype: int64

# DataFrame

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [40]:
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [41]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [42]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [44]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [45]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [46]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [47]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [48]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [50]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [51]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2['dept'] = val
frame2

year   state  pop  debt  dept
one    2000    Ohio  1.5   0.0   NaN
two    2001    Ohio  1.7   1.0  -1.2
three  2002    Ohio  3.6   2.0   NaN
four   2001  Nevada  2.4   3.0  -1.5
five   2002  Nevada  2.9   4.0  -1.7
six    2003  Nevada  3.2   5.0   NaN

In [52]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  dept  eastern
one    2000    Ohio  1.5   0.0   NaN     True
two    2001    Ohio  1.7   1.0  -1.2     True
three  2002    Ohio  3.6   2.0   NaN     True
four   2001  Nevada  2.4   3.0  -1.5    False
five   2002  Nevada  2.9   4.0  -1.7    False
six    2003  Nevada  3.2   5.0   NaN    False

In [53]:
del frame2['eastern']

In [54]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'dept'], dtype='object')

In [55]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [56]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [57]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [58]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [59]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [60]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [62]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [63]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [64]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [65]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [66]:
frame2.values

array([[2000, 'Ohio', 1.5, 0.0, nan],
       [2001, 'Ohio', 1.7, 1.0, -1.2],
       [2002, 'Ohio', 3.6, 2.0, nan],
       [2001, 'Nevada', 2.4, 3.0, -1.5],
       [2002, 'Nevada', 2.9, 4.0, -1.7],
       [2003, 'Nevada', 3.2, 5.0, nan]], dtype=object)

# Index Objects

In [67]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])

In [68]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [69]:
index[1:]

Index(['b', 'c'], dtype='object')

In [70]:
index[1] ='d'
# immutable

TypeError: Index does not support mutable operations

In [71]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [72]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [74]:
obj2.index is labels

True

In [75]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [76]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [77]:
2003 in frame3.index

False

In [78]:
# duplicate labels are possible
dup_labels =pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# Reindexing

In [79]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [80]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [81]:
# reindexing with filling the values for nan
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [82]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [87]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index = ['a', 'c', 'd'], columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [88]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [89]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [90]:
frame.loc[['a', 'b', 'c', 'd'], states]

C:\Users\Aditya\Anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

# Droping entries from axis

In [91]:
obj = pd.Series(np.arange(5.0), index = ['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [93]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [94]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [98]:
data = pd.DataFrame(np.arange(16).reshape((4, 4,)), index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [100]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [101]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [102]:
# modify object in place without returning a new object
obj.drop('c', inplace = True)

In [103]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

# Indexing, Selecting and Filtering

In [104]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [105]:
obj['b']

1.0

In [106]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [107]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [108]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [109]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [110]:
# end points are inclusive
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [111]:
obj['b':'c'] = 5

In [112]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [115]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                  columns = ['one','two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [118]:
data[['two', 'three']]

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [119]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [121]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
# using boolean indexing
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [124]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
# using loc and iloc
data.loc['Colorado', ['two' ,'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [126]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [127]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [128]:
data.iloc[[1, 2], [3, 0, 1]] 

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [133]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [135]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

# Integer Indexes

In [136]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [137]:
ser[-1]

KeyError: -1

In [138]:
ser2 = pd.Series(np.arange(3.), index = ['a', 'b', 'c'])

In [139]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [140]:
ser2[-1]

2.0

In [141]:
ser[:1]

0    0.0
dtype: float64

In [142]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [143]:
ser.iloc[:1]

0    0.0
dtype: float64

# Arithmetic and Data Alignment

In [144]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [145]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [146]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [148]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns = list('bcd'), index = ['Ohio', 'Texas', 'Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [149]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [150]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [151]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

A
0  1
1  2

In [152]:
df2 = pd.DataFrame({'B': [3, 4]})
df2

B
0  3
1  4

In [153]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

# Arithmetic Methods with fill values

In [157]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,  4)), columns = list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [159]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns = list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [162]:
df2.loc[1, 'b'] = np.nan

In [163]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [164]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [165]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [166]:
# using add method
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [167]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [168]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [169]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

# Operations between dataframe and series

In [170]:
arr = np.arange(12.).reshape((3,  4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [171]:
arr[0]

array([0., 1., 2., 3.])

In [172]:
arr-arr[0] # broadcasting

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [175]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [177]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [178]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [179]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [180]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [183]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [184]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [182]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# Function Application and Mapping

In [186]:
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.089955  1.878293  0.263439
Ohio    0.854753 -1.024987  0.334982
Texas   0.066352  1.163210  1.172291
Oregon -1.320430 -0.431696  0.565756

In [187]:
np.abs(frame)

b         d         e
Utah    0.089955  1.878293  0.263439
Ohio    0.854753  1.024987  0.334982
Texas   0.066352  1.163210  1.172291
Oregon  1.320430  0.431696  0.565756

In [188]:
f = lambda x: x.max() - x.min()

In [189]:
frame.apply(f)

b    2.175183
d    2.903280
e    0.908853
dtype: float64

In [190]:
frame.apply(f, axis = 'columns')

Utah      1.968248
Ohio      1.879740
Texas     1.105939
Oregon    1.886186
dtype: float64

In [191]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])
frame.apply(f)

b         d         e
min -1.320430 -1.024987  0.263439
max  0.854753  1.878293  1.172291

In [192]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d     e
Utah    -0.09   1.88  0.26
Ohio     0.85  -1.02  0.33
Texas    0.07   1.16  1.17
Oregon  -1.32  -0.43  0.57

In [193]:
frame['e'].map(format)

Utah      0.26
Ohio      0.33
Texas     1.17
Oregon    0.57
Name: e, dtype: object

# Sorting and Ranking

In [195]:
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [196]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [198]:
frame = pd.DataFrame(np.arange(8).reshape(2, 4), index = ['three', 'one'], columns = ['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [199]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [200]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [201]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [202]:
obj = pd.Series([4, 7, -3, 2])

In [203]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [205]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [206]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [207]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [208]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [210]:
# ranks
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [211]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [212]:
# rank according to which is observed first
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [213]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [214]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [215]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

# Axis Indexes with duplicate labels

In [216]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [217]:
obj.index.is_unique

False

In [218]:
# selection
obj['a']

a    0
a    1
dtype: int64

In [219]:
obj['c']

4

In [221]:
df = pd.DataFrame(np.random.randn(4, 3), index = ['a', 'a', 'b', 'b'])
df

0         1         2
a -0.597815 -0.280786  1.075524
a -0.592573 -0.346807 -1.555981
b  0.689105  0.305011 -1.433464
b -0.906036 -0.424433 -0.215754

In [222]:
df.loc['b']

0         1         2
b  0.689105  0.305011 -1.433464
b -0.906036 -0.424433 -0.215754

# Summarizing and Computing Descriptive Statistics

In [223]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index = ['a', 'b', 'c', 'd'], columns = ['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [224]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [225]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [226]:
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [227]:
df.idxmax() # maximum and minimum are attained

one    b
two    d
dtype: object

In [230]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [231]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [232]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [233]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [235]:
import pandas_datareader.data as web

In [236]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [238]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0   
 2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0   
 2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0   
 2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0   
 2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0   
 2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0   
 2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0   
 2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0   
 2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0   
 2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0   
 2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0   
 201

In [237]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

In [239]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [240]:
all_data.items()

dict_items([('AAPL',                   High         Low        Open       Close       Volume  \
Date                                                                      
2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0   
2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0   
2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0   
2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0   
2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0   
2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0   
2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0   
2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0   
2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0   
2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0   
2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0   
2010

In [241]:
returns = price.pct_change()

In [243]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-07-29  0.009339 -0.003171 -0.002193 -0.008797
2019-07-30 -0.004292 -0.007357 -0.004822 -0.011514
2019-07-31  0.020404 -0.010216 -0.029070 -0.006905
2019-08-01 -0.021639  0.014031  0.013136 -0.006304
2019-08-02 -0.021158 -0.020423 -0.008402 -0.012423

In [244]:
returns['MSFT'].corr(returns['IBM'])

0.48642448999988125

In [245]:
returns['MSFT'].cov(returns['IBM'])

8.633267747918666e-05

In [246]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.378498  0.451084  0.457257
IBM   0.378498  1.000000  0.486424  0.399875
MSFT  0.451084  0.486424  1.000000  0.533791
GOOG  0.457257  0.399875  0.533791  1.000000

In [247]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000265  0.000076  0.000106  0.000116
IBM   0.000076  0.000151  0.000086  0.000076
MSFT  0.000106  0.000086  0.000208  0.000120
GOOG  0.000116  0.000076  0.000120  0.000242

In [248]:
# pair wise
returns.corrwith(returns.IBM)

AAPL    0.378498
IBM     1.000000
MSFT    0.486424
GOOG    0.399875
dtype: float64

In [249]:
returns.corrwith(volume)

AAPL   -0.062038
IBM    -0.150972
MSFT   -0.090047
GOOG   -0.018750
dtype: float64

# Unique values, value counts and membership

In [250]:
obj = pd.Series(list('cadaabbcc'))
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [252]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [253]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [254]:
pd.value_counts(obj.values, sort = False)

b    2
a    3
c    3
d    1
dtype: int64

In [255]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [256]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [257]:
to_match = pd.Series(list('cabbca'))
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [258]:
unique_vals = pd.Series(list('cba'))
unique_vals

0    c
1    b
2    a
dtype: object

In [259]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [261]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qu2': [2, 3, 1, 2, 3],
                    'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [262]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0