In [2]:
import numpy as np

# using randn function

In [5]:
data = np.random.randn(2,3)
data

array([[ 0.2130838 ,  0.09607895, -0.32976562],
       [-1.95687428,  0.18350042,  1.48221733]])

In [6]:
data * 10

array([[  2.13083796,   0.96078946,  -3.29765624],
       [-19.5687428 ,   1.83500423,  14.82217333]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

# creation of array

In [9]:
data1 = [6, 7.5, 8, 0, 1]

In [10]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# creating empty arrays

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
# (times, rows, columns)
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

# creating string type array

In [26]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

# type conversion

In [28]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [30]:
int_arr = np.arange(10)
int_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
float_arr = np.array([1, 2, 3, 4], dtype = np.float64)
float_arr

array([1., 2., 3., 4.])

In [34]:
int_arr.astype(float_arr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# batchprocessing using arrays

In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [39]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [42]:
arr ** 5

array([[1.000e+00, 3.200e+01, 2.430e+02],
       [1.024e+03, 3.125e+03, 7.776e+03]])

In [43]:
arr2 = np.array([[12, 1, 4], [2, 3, 18]], dtype = np.float64)
arr2

array([[12.,  1.,  4.],
       [ 2.,  3., 18.]])

In [44]:
arr2 > arr

array([[ True, False,  True],
       [False, False,  True]])

# Indexing

In [45]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]

5

In [47]:
arr[5:8]

array([5, 6, 7])

In [48]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [49]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

## slice effects the original array

In [50]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [51]:
arr_slice = arr[5:8].copy()
arr_slice

array([   12, 12345,    12])

In [52]:
arr_slice[1] = 12
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [53]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[2]

array([7, 8, 9])

In [55]:
arr2d[0][2]

3

In [56]:
arr2d[0, 2]

3

In [79]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr3d[0][1]

array([4, 5, 6])

In [82]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [85]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# indexing with slices

In [86]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [91]:
arr2d[:, 2]

array([3, 6, 9])

# Boolean indexing (always creates a copy)

In [93]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [94]:
data = np.random.randn(7 ,4)
data

array([[ 1.23051238, -1.80155154,  0.2915994 ,  0.5563227 ],
       [-0.7768142 , -0.32824571,  0.84851161,  1.30934711],
       [-0.59068622,  0.02487111, -0.58161781, -0.51985479],
       [ 0.84663914, -0.51221623,  1.15869741,  0.54157521],
       [ 0.25261303,  0.48333058,  0.90621355, -0.54667572],
       [ 1.11158778,  0.60387742,  1.42878516, -0.77120391],
       [ 0.0645321 ,  0.9480471 ,  0.74996226, -1.20224798]])

In [96]:
'bob' in names

True

In [97]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [98]:
# rows in data with same index bob == true
data[names == 'bob']

array([[ 1.23051238, -1.80155154,  0.2915994 ,  0.5563227 ],
       [ 0.84663914, -0.51221623,  1.15869741,  0.54157521]])

In [99]:
data[names == 'bob', 2:]

array([[0.2915994 , 0.5563227 ],
       [1.15869741, 0.54157521]])

In [100]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True])

In [101]:
data[names != 'bob']

array([[-0.7768142 , -0.32824571,  0.84851161,  1.30934711],
       [-0.59068622,  0.02487111, -0.58161781, -0.51985479],
       [ 0.25261303,  0.48333058,  0.90621355, -0.54667572],
       [ 1.11158778,  0.60387742,  1.42878516, -0.77120391],
       [ 0.0645321 ,  0.9480471 ,  0.74996226, -1.20224798]])

In [103]:
cond = names == 'bob'
cond

array([ True, False, False,  True, False, False, False])

In [104]:
data[cond]

array([[ 1.23051238, -1.80155154,  0.2915994 ,  0.5563227 ],
       [ 0.84663914, -0.51221623,  1.15869741,  0.54157521]])

In [105]:
data[~cond]

array([[-0.7768142 , -0.32824571,  0.84851161,  1.30934711],
       [-0.59068622,  0.02487111, -0.58161781, -0.51985479],
       [ 0.25261303,  0.48333058,  0.90621355, -0.54667572],
       [ 1.11158778,  0.60387742,  1.42878516, -0.77120391],
       [ 0.0645321 ,  0.9480471 ,  0.74996226, -1.20224798]])

In [107]:
mask = (names == 'bob') | (names == 'will')
mask

array([ True, False,  True,  True,  True, False, False])

In [108]:
data[mask]

array([[ 1.23051238, -1.80155154,  0.2915994 ,  0.5563227 ],
       [-0.59068622,  0.02487111, -0.58161781, -0.51985479],
       [ 0.84663914, -0.51221623,  1.15869741,  0.54157521],
       [ 0.25261303,  0.48333058,  0.90621355, -0.54667572]])